export const TO_NEXT_PAGE = 'TO_NEXT_PAGE'
export const TO_PREVIOUS_PAGE = 'TO_PREVIOUS_PAGE'
export const BEER_LIST_SET_STATE = 'BEER_LIST_SET_STATE'
export const CONTROLS_SET_STATE = 'CONTROLS_SET_STATE'

export const REMOVE_FAVOURITE_BEER = 'REMOVE_FAVOURITE_BEER'
export const ADD_FAVOURITE_BEER = 'ADD_FAVOURITE_BEER'

export const SET_ACTIVE_BEER = 'SET_ACTIVE_BEER'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const RESET_FAVOURITE_LIST = 'RESET_FAVOURITE_LIST'
export const SET_FAVOURITE_LIST = 'SET_FAVOURITE_LIST'